-- Create Movies Table 
CREATE TABLE Movies
    (ID VARCHAR(255),
     TITLE VARCHAR(255),
     YEAR VARCHAR(255),
     POSTER VARCHAR(255),
     LIKED BOOLEAN,
     CONSTRAINT MOVIE_PK PRIMARY KEY(ID));